"""empty message

Revision ID: 0b26c9fc5f36
Revises: a4e5aaf72242
Create Date: 2024-07-19 19:29:06.359909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b26c9fc5f36'
down_revision = 'a4e5aaf72242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pais')

    # ### end Alembic commands ###
