"""empty message

Revision ID: a4e5aaf72242
Revises: 0fe3c6ef59cc
Create Date: 2024-07-19 19:28:22.769491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e5aaf72242'
down_revision = '0fe3c6ef59cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pais')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
